**Exercício para praticar - > Pandas**

In [22]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_csv("Itau_historical_stock_data_(2002-2026).csv")

In [24]:
df

            Date     Close      High       Low      Open    Volume
0     2002-02-25  0.427699  0.427699  0.411483  0.411685   2452314
1     2002-02-26  0.441569  0.443090  0.422304  0.425346  28467421
2     2002-02-27  0.441062  0.443090  0.434573  0.442178   9613757
3     2002-02-28  0.435486  0.437007  0.435182  0.437007  13520310
4     2002-03-01  0.425853  0.434471  0.420276  0.434471   3570432
...          ...       ...       ...       ...       ...       ...
6043  2026-03-03  8.400000  8.520000  8.120000  8.350000  40625200
6044  2026-03-04  8.610000  8.670000  8.530000  8.560000  34517300
6045  2026-03-05  8.260000  8.430000  8.190000  8.400000  26476800
6046  2026-03-06  8.140000  8.210000  8.050000  8.070000  26417800
6047  2026-03-09  8.290000  8.350000  8.070000  8.130000  40223100

[6048 rows x 6 columns]

**Exercício 1**
  - Carregue o dataset e descubra o tamanho dele. Responda nos comentários quantos dias de negociação tem no histórico.

In [25]:
df.shape
#Resposta ->   6048 dias.

(6048, 6)

**Exercício 2**

   - Visualize as primeiras 10 linhas e as últimas 5 linhas.

In [26]:
df.head(10)

         Date     Close      High       Low      Open    Volume
0  2002-02-25  0.427699  0.427699  0.411483  0.411685   2452314
1  2002-02-26  0.441569  0.443090  0.422304  0.425346  28467421
2  2002-02-27  0.441062  0.443090  0.434573  0.442178   9613757
3  2002-02-28  0.435486  0.437007  0.435182  0.437007  13520310
4  2002-03-01  0.425853  0.434471  0.420276  0.434471   3570432
5  2002-03-04  0.428895  0.428895  0.423319  0.427881    720260
6  2002-03-05  0.406589  0.428794  0.405574  0.427780   2850172
7  2002-03-06  0.402533  0.404054  0.395435  0.400505   2239666
8  2002-03-07  0.408616  0.410644  0.404053  0.410644   1546844
9  2002-03-08  0.408109  0.409630  0.406081  0.409630    463024

**Exercício 3**

  - Descubra os nomes de todas as colunas e responda nos comentários o que cada uma representa.

      - Date → data do pregão
      - Close → preço de fechamento
      - High → preço máximo do dia
      - Low → preço mínimo do dia
      - Open → preço de abertura
      - Volume → quantidade de ações negociadas

In [27]:
df.columns

Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

**Exercício 4**

  - Verifique as informações gerais do dataset e responda nos comentários quantas colunas são numéricas e quantas são texto.

In [28]:
df.info()
# Colunas Numéricas: 5 
# Colunas Textos: 1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6048 entries, 0 to 6047
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    6048 non-null   object
 1   Close   6048 non-null   float64
 2   High    6048 non-null   float64
 3   Low     6048 non-null   float64
 4   Open    6048 non-null   float64
 5   Volume  6048 non-null   int64
dtypes: float64(4), int64(1), object(1)
memory usage: 283.6+ KB

**Exercício 5**

 -  Verifique se há valores nulos e duplicatas. Responda nos comentários se o dataset está limpo.

**Valores nulos**

In [29]:
df.isnull()

       Date  Close   High    Low   Open  Volume
0     False  False  False  False  False   False
1     False  False  False  False  False   False
2     False  False  False  False  False   False
3     False  False  False  False  False   False
4     False  False  False  False  False   False
...     ...    ...    ...    ...    ...     ...
6043  False  False  False  False  False   False
6044  False  False  False  False  False   False
6045  False  False  False  False  False   False
6046  False  False  False  False  False   False
6047  False  False  False  False  False   False

[6048 rows x 6 columns]

In [30]:
df.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

**Linhas duplicadas**

In [31]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
6043    False
6044    False
6045    False
6046    False
6047    False
Length: 6048, dtype: bool

In [32]:
df.duplicated().sum()

0

**Exercício 6**

  - Mostre as estatísticas gerais formatadas com 2 casas decimais. Responda nos comentários qual foi o maior e menor preço de fechamento da história.

In [33]:
with pd.option_context("float_format", "{:.2f}".format):
    display(df.describe())

    #Menor valor: 0.15
    #Maior valor: 9.57

        Close    High     Low    Open       Volume
count 6048.00 6048.00 6048.00 6048.00      6048.00
mean     2.88    2.92    2.84    2.88  26104280.93
std      1.46    1.47    1.44    1.45  18821372.92
min      0.15    0.16    0.15    0.15     20579.00
25%      2.02    2.06    1.99    2.03  12897283.25
50%      2.97    3.01    2.92    2.98  23105233.00
75%      3.68    3.72    3.63    3.68  35297353.75
max      9.57    9.60    9.42    9.52 205942244.00

**Exercício 7**

  - Separe as colunas numéricas das colunas de texto. Responda nos comentários quantas colunas de cada tipo existem.

In [34]:
df.select_dtypes("number")

#Colunas numericas existentes: 5
#Colunas textos existentes: 1

         Close      High       Low      Open    Volume
0     0.427699  0.427699  0.411483  0.411685   2452314
1     0.441569  0.443090  0.422304  0.425346  28467421
2     0.441062  0.443090  0.434573  0.442178   9613757
3     0.435486  0.437007  0.435182  0.437007  13520310
4     0.425853  0.434471  0.420276  0.434471   3570432
...        ...       ...       ...       ...       ...
6043  8.400000  8.520000  8.120000  8.350000  40625200
6044  8.610000  8.670000  8.530000  8.560000  34517300
6045  8.260000  8.430000  8.190000  8.400000  26476800
6046  8.140000  8.210000  8.050000  8.070000  26417800
6047  8.290000  8.350000  8.070000  8.130000  40223100

[6048 rows x 5 columns]

In [35]:
df.select_dtypes("object")

            Date
0     2002-02-25
1     2002-02-26
2     2002-02-27
3     2002-02-28
4     2002-03-01
...          ...
6043  2026-03-03
6044  2026-03-04
6045  2026-03-05
6046  2026-03-06
6047  2026-03-09

[6048 rows x 1 columns]

**Exercício 8**

  -  Descubra quantos valores únicos tem cada coluna. Responda nos comentários qual coluna tem mais valores únicos.

In [36]:
df.nunique()
#Coluna com mais valores unicos: Date -> 6048

Date      6048
Close     5593
High      6011
Low       6029
Open      6036
Volume    5876
dtype: int64

**Exercício 9**

  - Use value_counts() na coluna Volume e descubra se algum volume se repetiu. Responda nos comentários o que encontrou.

In [37]:
df["Volume"].value_counts()
# Algum repetiu? Sim

Volume
3045671     4
1972141     4
4438174     4
2548349     4
1718335     3
           ..
19978505    1
19984541    1
22063555    1
32107684    1
40223100    1
Name: count, Length: 5876, dtype: int64

**Exercício 10 — Desafio**

  - Faça a checagem básica completa do dataset e escreva um comentário resumindo tudo — como se fosse apresentar pro seu gestor no Itaú:

      -  Quantos dias de negociação?

      -  Dataset limpo?

      -  Maior e menor preço?
      
      -  Volume médio?

In [38]:
#Dias de negociação - > 6048
df.shape

(6048, 6)

In [39]:
# Dataset limpo?(Linhas duplicadas, valores nuloes e etc)
#Sim. 
df.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [40]:
df.duplicated().sum()

0

**MAIOR E MENOR PREÇO**

In [41]:
#Maior -> 9.59
#Menor -> 0.15
df.describe()

             Close         High          Low         Open        Volume
count  6048.000000  6048.000000  6048.000000  6048.000000  6.048000e+03
mean      2.882616     2.921363     2.841746     2.882150  2.610428e+07
std       1.455131     1.468384     1.441096     1.454242  1.882137e+07
min       0.153030     0.157298     0.148345     0.150948  2.057900e+04
25%       2.023648     2.055508     1.988603     2.028130  1.289728e+07
50%       2.971818     3.012947     2.922061     2.975265  2.310523e+07
75%       3.676547     3.722738     3.634823     3.677427  3.529735e+07
max       9.566759     9.596750     9.416810     9.516777  2.059422e+08

In [42]:
#Volume médio -> 26104280.930390213
np.mean(df["Volume"])

26104280.930390213